export type Category = {
  slug: string;
  name: string;
  short: string;
  tagline: string;
  description: string;
  image: string;
  pressure: string;
  featured: boolean;
  hover: string;
};

export type Product = {
  slug: string;
  code: string;
  name: string;
  category: string;
  summary: string;
  description: string;
  image: string;
  port: string;
  pressurePsi: number;
  pressureGasPsi?: number;
  pressureLabel: string;
  media: string[];
  materials: string[];
  applications: string[];
  industries: string[];
  mounting: string;
  features: string[];
  specs: { label: string; value: string }[];
};

export const categories: Category[] = [
  {
    slug: "solenoid-valves",
    name: "Solenoid Valves",
    short: "Solenoid",
    tagline: "Direct-acting and piloted switching to 10,000 psi.",
    description:
      "Stainless steel solenoid valves from the smallest low-pressure pneumatic 2/2 valves to 1\" directional valves for high-pressure liquids. Direct-acting and pilot-operated designs for topside and subsea, with ATEX and IECEx coils from 3 watts, manual override and reset options.",
    image: "/images/solenoid.jpg",
    pressure: "10,000 psi",
    featured: true,
    hover: "2/3 port · ATEX · subsea coils",
  },
  {
    slug: "directional-control-valves",
    name: "Directional Control Valves",
    short: "Directional",
    tagline: "3-port and 4-port control. Independent of line pressure.",
    description:
      "Balanced poppet 3-port valves and 4-port rotary shear-seal designs for gases, seawater and aggressive chemicals. Actuation is independent of main-line pressure, with a vent chamber isolating pilot and process fluids. Hydraulic, pneumatic, lever and cam operators.",
    image: "/images/directional.jpg",
    pressure: "10,000 psi",
    featured: true,
    hover: "3-port & 4-port · poppet & shear seal",
  },
  {
    slug: "stop-metering-valves",
    name: "Stop & Metering Valves",
    short: "Stop & Metering",
    tagline: "Positive shut-off and micrometer flow control.",
    description:
      "Inline, manifold-mounted and cartridge stop valves for tight shut-off, plus graduated micrometer metering valves and pressure-compensated flow regulators that hold rate as load or supply pressure changes.",
    image: "/images/stop-metering.jpg",
    pressure: "10,000 psi",
    featured: true,
    hover: "Shut-off · micrometer · compensated flow",
  },
  {
    slug: "check-shuttle-valves",
    name: "Check & Shuttle Valves",
    short: "Check & Shuttle",
    tagline: "Zero-leak isolation and redundant pilot selection.",
    description:
      "Inline and cartridge check valves from 1/4\" to 2\" for liquids and gases to 20,000 psi. Shuttle valves select the higher of two pressures — a function often used when redundancy of pilot systems is required.",
    image: "/images/check.jpg",
    pressure: "20,000 psi",
    featured: true,
    hover: "1/4\"–2\" · cartridge · shuttle",
  },
  {
    slug: "relief-valves",
    name: "Relief Valves",
    short: "Relief",
    tagline: "Category IV safety accessories to 20,000 psi.",
    description:
      "Safety relief and relief valves from low-pressure vent-to-atmosphere designs to high-pressure piped-return valves at 1,379 bar. CE marked as Category IV safety accessories under PED 2014/68/EU. Cartridge, manifold and exotic-material options.",
    image: "/images/relief.jpg",
    pressure: "20,000 psi",
    featured: true,
    hover: "PED Cat. IV · 0.7–20,000 psi",
  },
  {
    slug: "pressure-sensing-valves",
    name: "Pressure Sensing Valves",
    short: "Pressure Sensing",
    tagline: "Pilot signals triggered by a second service.",
    description:
      "3SV sensing valves provide a low-pressure signal switch dependent on a separate sensed pressure of up to 414 bar (6,000 psi) — used to actuate another valve when a second service rises or falls beyond a pre-set pressure.",
    image: "/images/pressure-sensing.jpg",
    pressure: "6,000 psi",
    featured: true,
    hover: "Pilot switch · 6,000 psi sensed",
  },
  {
    slug: "manifolds",
    name: "Manifolds",
    short: "Manifolds",
    tagline: "A circuit, packaged as one block.",
    description:
      "Bespoke manifold solutions for topside and subsea, typically in 316 stainless. Designed from the customer's circuit diagram, packing BiS valves into a compact block that cuts leak points, installation time and service disruption.",
    image: "/images/manifold.jpg",
    pressure: "Application rated",
    featured: true,
    hover: "Topside & subsea · 316 stainless",
  },
  {
    slug: "bespoke",
    name: "Bespoke / Custom Solutions",
    short: "Bespoke",
    tagline: "When the standard range is not enough.",
    description:
      "The catalogue is a fraction of what BiS manufactures. Over 50 years of specialist supply means a suitable product is often available from the back catalogue — and when it is not, the engineering team designs the valve around the fluid, pressure and envelope. Super duplex, Monel, Inconel, Hastelloy and titanium.",
    image: "/images/bespoke.jpg",
    pressure: "To 20,000 psi",
    featured: true,
    hover: "Exotic alloys · application-led",
  },
  {
    slug: "excess-flow-valves",
    name: "Excess Flow Valves",
    short: "Excess Flow",
    tagline: "Shut the line if the hose goes.",
    description:
      "Designed to the standards of oil & gas and petrochemical service. Primary function is to shut a line down in the event of breakage or rupture of a downstream pipe or hose, or any application where excessive flow must be avoided.",
    image: "/images/check.jpg",
    pressure: "6,000 psi",
    featured: false,
    hover: "Rupture protection · adjustable",
  },
  {
    slug: "filters",
    name: "Filters",
    short: "Filters",
    tagline: "Protect the seat. Protect the system.",
    description:
      "From small component-protection strainers to full-pressure main-line units. F and EF series protect against rogue debris; SF and DF simplex and duplex filters offer bypasses, clogging indicators and on-line servicing.",
    image: "/images/filter.jpg",
    pressure: "12,000 psi",
    featured: false,
    hover: "Inline · simplex · duplex",
  },
  {
    slug: "pumps",
    name: "Pumps",
    short: "Pumps",
    tagline: "Low flow. High pressure.",
    description:
      "Low-flow radial piston pumps offering pressures up to 827 bar (12,000 psi). Designed primarily for mineral oil, with limited use on water glycols.",
    image: "/images/high-pressure.jpg",
    pressure: "12,000 psi",
    featured: false,
    hover: "Radial piston · 12,000 psi",
  },
  {
    slug: "actuators",
    name: "Actuators & Solenoid Thrusters",
    short: "Actuators",
    tagline: "Pneumatic, hydraulic, manual and ATEX.",
    description:
      "A comprehensive range of actuators for the BiS product family: pneumatic or hydraulic, diaphragm or piston, plus solenoid thrusters — including Baseefa-approved hazardous-area and subsea coils — and manual rotary and linear operators.",
    image: "/images/actuator.jpg",
    pressure: "Matched to valve",
    featured: false,
    hover: "ATEX · subsea · lever & cam",
  },
  {
    slug: "pilot-operated-check-valves",
    name: "Pilot Operated Check Valves",
    short: "Pilot Check",
    tagline: "Load holding, decompression and unloaders.",
    description:
      "Single and dual pilot-operated checks, decompression checks designed to reduce shock when a high-pressure line is opened, and unloader valves. Hydraulic or pneumatic pilot, lever or cam actuation.",
    image: "/images/check.jpg",
    pressure: "20,000 psi",
    featured: false,
    hover: "POC · decompression · unloader",
  },
];

const SS = ["316 stainless steel"];
const EXOTIC = [
  "316 stainless steel",
  "Super duplex",
  "Monel",
  "Inconel",
  "Hastelloy",
  "Titanium",
];

function psiLabel(liquid: number, gas?: number) {
  if (gas && gas !== liquid) return `${liquid.toLocaleString()} psi liquid / ${gas.toLocaleString()} psi gas`;
  return `${liquid.toLocaleString()} psi`;
}

function p(partial: Omit<Product, "specs"> & { specs?: Product["specs"] }): Product {
  return {
    ...partial,
    specs: partial.specs ?? [
      { label: "Model", value: partial.code },
      { label: "Port size", value: partial.port },
      { label: "Operating pressure", value: partial.pressureLabel },
      { label: "Body material", value: partial.materials[0] },
      { label: "Mounting", value: partial.mounting },
      { label: "Media", value: partial.media.join(", ") },
    ],
  };
}

export const products: Product[] = [
  p({
    slug: "2-3as25",
    code: "2/3AS25",
    name: "Direct Solenoid Valve",
    category: "solenoid-valves",
    summary: "2-position 3-way direct-acting stainless solenoid for 16 bar gas and liquid.",
    description:
      "The 2/3AS25 is a 2-position 3-way direct-acting stainless steel solenoid valve for pressures to 16 bar with gas and liquid. A balanced design enables normally closed, normally open and selector configurations — an ideal choice for low-pressure pneumatic switching. Low-wattage thrusters include ATEX and IECEx coils, with override and reset options.",
    image: "/images/solenoid.jpg",
    port: "1/4\"",
    pressurePsi: 232,
    pressureLabel: "16 bar",
    media: ["Air", "Gas", "Liquid"],
    materials: SS,
    applications: ["Low-pressure pneumatic switching", "Pilot duty"],
    industries: ["topside", "industrial-gas", "specialist-engineering"],
    mounting: "Ported",
    features: ["Balanced design", "NC / NO / selector", "ATEX coil options", "Manual override"],
  }),
  p({
    slug: "2-3ds20-25",
    code: "2/3DS20/25",
    name: "Direct Solenoid Valve",
    category: "solenoid-valves",
    summary: "Stainless steel pilot-size solenoid valve for pressures to 10,000 psi.",
    description:
      "Stainless steel pilot-size solenoid valve for pressures to 10,000 psi. Direct-acting construction for low-flow, high-pressure switching with a wide range of thrusters including hazardous-area coils.",
    image: "/images/solenoid.jpg",
    port: "Pilot",
    pressurePsi: 10000,
    pressureLabel: "10,000 psi",
    media: ["Oil", "Water glycol", "Liquid"],
    materials: SS,
    applications: ["High-pressure pilot", "Low-flow switching"],
    industries: ["oil-and-gas", "topside", "high-pressure-systems"],
    mounting: "Ported",
    features: ["Direct acting", "10,000 psi", "Hazardous-area coils"],
  }),
  p({
    slug: "2-3ds25",
    code: "2/3DS25",
    name: "Direct Solenoid Valve",
    category: "solenoid-valves",
    summary: "1/4\" soft-seated solenoid to 6,000 psi liquid and 3,500 psi gas.",
    description:
      "1/4\" stainless steel soft-seated solenoid valve for pressures to 6,000 psi with liquid and 3,500 psi with gas. Direct acting, with ATEX/IECEx thrusters, override and reset options.",
    image: "/images/solenoid.jpg",
    port: "1/4\"",
    pressurePsi: 6000,
    pressureGasPsi: 3500,
    pressureLabel: psiLabel(6000, 3500),
    media: ["Oil", "Gas", "Water glycol"],
    materials: SS,
    applications: ["High-pressure switching", "Gas service"],
    industries: ["oil-and-gas", "topside", "industrial-gas"],
    mounting: "Ported or manifold",
    features: ["Soft seated", "Gas rated", "ATEX options"],
  }),
  p({
    slug: "2-3ds37",
    code: "2/3DS37",
    name: "Direct Solenoid Valve",
    category: "solenoid-valves",
    summary: "3/8\" soft-seated solenoid to 6,000 psi liquid and 3,500 psi gas.",
    description:
      "3/8\" ported stainless steel soft-seated solenoid valve for pressures to 6,000 psi with liquid and 3,500 psi with gas.",
    image: "/images/solenoid.jpg",
    port: "3/8\"",
    pressurePsi: 6000,
    pressureGasPsi: 3500,
    pressureLabel: psiLabel(6000, 3500),
    media: ["Oil", "Gas", "Water glycol"],
    materials: SS,
    applications: ["Directional switching", "Gas service"],
    industries: ["oil-and-gas", "topside"],
    mounting: "Ported",
    features: ["Soft seated", "3/8\" ports"],
  }),
  p({
    slug: "2-3ds01",
    code: "2/3DS01",
    name: "Direct Solenoid Valve",
    category: "solenoid-valves",
    summary: "2-position 3-way normally closed solenoid to 10,000 psi liquid.",
    description:
      "The 2/3DS01 is a 2-position 3-way direct-acting stainless steel solenoid valve for pressures to 10,000 psi with liquid. Configured normally closed — an ideal choice for low-flow, high-pressure switching. Low-wattage thrusters include ATEX and IECEx coils, with override and reset options.",
    image: "/images/solenoid.jpg",
    port: "Compact",
    pressurePsi: 10000,
    pressureLabel: "10,000 psi liquid",
    media: ["Oil", "Water glycol", "Liquid"],
    materials: SS,
    applications: ["Low-flow high-pressure switching"],
    industries: ["oil-and-gas", "high-pressure-systems", "subsea"],
    mounting: "Ported",
    features: ["Normally closed", "10,000 psi", "Manual override"],
  }),
  p({
    slug: "2-3eps25",
    code: "2/3EPS25",
    name: "In-Direct Solenoid Valve",
    category: "solenoid-valves",
    summary: "1/4\" externally piloted balanced poppet solenoid to 10,000 psi.",
    description:
      "The 2/3EPS25 is a 1/4\" stainless steel balanced poppet 2-position 3-port externally piloted solenoid valve for pressures to 10,000 psi with liquid. Pilot-operated construction controls higher flow rates using a direct-acting valve as the pilot element.",
    image: "/images/solenoid.jpg",
    port: "1/4\"",
    pressurePsi: 10000,
    pressureLabel: "10,000 psi liquid",
    media: ["Oil", "Water glycol"],
    materials: SS,
    applications: ["High-flow solenoid control", "Main-stage piloting"],
    industries: ["oil-and-gas", "topside", "high-pressure-systems"],
    mounting: "Ported",
    features: ["Externally piloted", "Balanced poppet", "ATEX coils"],
  }),
  p({
    slug: "subsea-solenoid-valves",
    code: "SUBSEA",
    name: "Subsea Solenoid Valves",
    category: "solenoid-valves",
    summary: "Subsea solenoid constructions — specified with the engineering team.",
    description:
      "Subsea solenoid valves are offered for wellhead, ESD and ROV systems. Coil, connector and material selections are application-specific. Contact BiS to discuss ambient pressure, fluid and electrical interface.",
    image: "/images/solenoid.jpg",
    port: "Application",
    pressurePsi: 10000,
    pressureLabel: "Application rated",
    media: ["Seawater", "Oil", "Water glycol"],
    materials: EXOTIC,
    applications: ["Subsea wellhead", "ROV", "ESD"],
    industries: ["subsea", "oil-and-gas"],
    mounting: "Application",
    features: ["Subsea coils", "Hyperbaric capable", "Bespoke connectors"],
  }),

  p({
    slug: "3b25",
    code: "3B25",
    name: "Directional Control Valve",
    category: "directional-control-valves",
    summary: "1/4\" balanced poppet 2-position 3-port valve to 10,000 psi.",
    description:
      "1/4\" stainless steel balanced poppet 2-position 3-port directional control valve with hydraulic, pneumatic, cam and lever operators, for pressures to 10,000 psi. Actuation is independent of main-line pressure, with a vent chamber between main ports and the pilot system.",
    image: "/images/directional.jpg",
    port: "1/4\"",
    pressurePsi: 10000,
    pressureLabel: "10,000 psi",
    media: ["Oil", "Gas", "Seawater", "Chemicals"],
    materials: SS,
    applications: ["Directional control", "Pilot isolation"],
    industries: ["oil-and-gas", "topside", "subsea"],
    mounting: "Ported",
    features: ["Balanced poppet", "Independent actuation", "Vent chamber"],
  }),
  p({
    slug: "3b25-g",
    code: "3B25-G",
    name: "Directional Control Valve",
    category: "directional-control-valves",
    summary: "1/4\" soft-seated 3-port valve to 6,000 psi liquid / 3,500 psi gas.",
    description:
      "1/4\" stainless steel soft-seated balanced poppet 2-position 3-port directional control valve with hydraulic, pneumatic, cam and lever operators.",
    image: "/images/directional.jpg",
    port: "1/4\"",
    pressurePsi: 6000,
    pressureGasPsi: 3500,
    pressureLabel: psiLabel(6000, 3500),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Gas directional control"],
    industries: ["industrial-gas", "oil-and-gas"],
    mounting: "Ported",
    features: ["Soft seated", "Gas rated"],
  }),
  p({
    slug: "3b37",
    code: "3B37",
    name: "Directional Control Valve",
    category: "directional-control-valves",
    summary: "3/8\" balanced poppet 3-port valve to 10,000 psi.",
    description:
      "3/8\" balanced poppet 2-position 3-port directional control valve with hydraulic, pneumatic, cam and lever operators, for pressures to 10,000 psi.",
    image: "/images/directional.jpg",
    port: "3/8\"",
    pressurePsi: 10000,
    pressureLabel: "10,000 psi",
    media: ["Oil", "Seawater", "Chemicals"],
    materials: SS,
    applications: ["Directional control"],
    industries: ["oil-and-gas", "topside"],
    mounting: "Ported",
    features: ["Balanced poppet", "Multiple operators"],
  }),
  p({
    slug: "3b37-g",
    code: "3B37-G",
    name: "Directional Control Valve",
    category: "directional-control-valves",
    summary: "3/8\" soft-seated 3-port valve to 6,000 psi liquid / 3,500 psi gas.",
    description:
      "3/8\" soft-seated balanced poppet 2-position 3-port directional control valve with hydraulic, pneumatic, cam and lever operators.",
    image: "/images/directional.jpg",
    port: "3/8\"",
    pressurePsi: 6000,
    pressureGasPsi: 3500,
    pressureLabel: psiLabel(6000, 3500),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Gas directional control"],
    industries: ["industrial-gas", "oil-and-gas"],
    mounting: "Ported",
    features: ["Soft seated"],
  }),
  p({
    slug: "3b50",
    code: "3B50",
    name: "Directional Control Valve",
    category: "directional-control-valves",
    summary: "1/2\" balanced poppet 3-port valve to 10,000 psi.",
    description:
      "1/2\" stainless steel balanced poppet 2-position 3-port directional control valve with hydraulic, pneumatic, cam and lever operators, for pressures to 10,000 psi.",
    image: "/images/directional.jpg",
    port: "1/2\"",
    pressurePsi: 10000,
    pressureLabel: "10,000 psi",
    media: ["Oil", "Seawater"],
    materials: SS,
    applications: ["Directional control"],
    industries: ["oil-and-gas", "topside"],
    mounting: "Ported",
    features: ["Balanced poppet"],
  }),
  p({
    slug: "3b50-g",
    code: "3B50-G",
    name: "Directional Control Valve",
    category: "directional-control-valves",
    summary: "1/2\" soft-seated 3-port valve to 6,000 psi liquid / 3,500 psi gas.",
    description:
      "1/2\" stainless steel soft-seated balanced poppet 2-position 3-port directional control valve.",
    image: "/images/directional.jpg",
    port: "1/2\"",
    pressurePsi: 6000,
    pressureGasPsi: 3500,
    pressureLabel: psiLabel(6000, 3500),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Gas directional control"],
    industries: ["industrial-gas"],
    mounting: "Ported",
    features: ["Soft seated"],
  }),
  p({
    slug: "3bhf100",
    code: "3BHF100",
    name: "Directional Control Valve",
    category: "directional-control-valves",
    summary: "1\" soft-seated 3-port valve to 3,500 psi liquid or gas.",
    description:
      "1\" stainless steel soft-seated balanced poppet 2-position 3-port directional control valve with hydraulic, pneumatic and lever operators, for pressures to 3,500 psi with liquid or gas.",
    image: "/images/directional.jpg",
    port: "1\"",
    pressurePsi: 3500,
    pressureLabel: "3,500 psi liquid or gas",
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["High-flow directional control"],
    industries: ["oil-and-gas", "industrial-gas"],
    mounting: "Ported",
    features: ["1\" ports", "Soft seated"],
  }),
  p({
    slug: "4r25",
    code: "4R25",
    name: "Rotary Control Valve",
    category: "directional-control-valves",
    summary: "1/4\" 3-position 4-port shear-seal rotary valve to 10,000 psi.",
    description:
      "1/4\" stainless steel 3-position 4-port shear-seal rotary directional control valve for pressures up to 10,000 psi. 90° manual actuation in detented and non-detented configurations, with a range of centre conditions. Threaded, manifold or panel mounting.",
    image: "/images/directional.jpg",
    port: "1/4\"",
    pressurePsi: 10000,
    pressureLabel: "10,000 psi",
    media: ["Oil", "Water glycol"],
    materials: SS,
    applications: ["Double-acting actuator control", "Manual 4-way"],
    industries: ["oil-and-gas", "topside", "specialist-engineering"],
    mounting: "Ported, manifold or panel",
    features: ["Shear seal", "3-position", "90° actuation"],
  }),
  p({
    slug: "4r37",
    code: "4R37",
    name: "Rotary Control Valve",
    category: "directional-control-valves",
    summary: "3/8\" 3-position 4-port shear-seal rotary valve to 6,000 psi.",
    description:
      "3/8\" stainless steel 3-position 4-port shear-seal rotary directional control valve for pressures up to 6,000 psi.",
    image: "/images/directional.jpg",
    port: "3/8\"",
    pressurePsi: 6000,
    pressureLabel: "6,000 psi",
    media: ["Oil", "Water glycol"],
    materials: SS,
    applications: ["Manual 4-way control"],
    industries: ["oil-and-gas", "topside"],
    mounting: "Ported, manifold or panel",
    features: ["Shear seal", "3-position"],
  }),
  p({
    slug: "6b37-a3",
    code: "6B37-A3",
    name: "Directional Control Valve",
    category: "directional-control-valves",
    summary: "3/8\" 2-position 4-port valve with pneumatic or LP hydraulic pilot to 10,000 psi.",
    description:
      "3/8\" 2-position 4-port directional control valve with pneumatic or low-pressure hydraulic pilot actuation for pressures up to 10,000 psi.",
    image: "/images/directional.jpg",
    port: "3/8\"",
    pressurePsi: 10000,
    pressureLabel: "10,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Remote 4-way control"],
    industries: ["oil-and-gas", "topside"],
    mounting: "Ported",
    features: ["Pneumatic / LP hydraulic pilot"],
  }),
  p({
    slug: "6b37-a3-g",
    code: "6B37-A3-G",
    name: "Directional Control Valve",
    category: "directional-control-valves",
    summary: "3/8\" soft-seated 4-port valve, pneumatic or LP hydraulic pilot.",
    description:
      "3/8\" 2-position 4-port soft-seated directional control valve with pneumatic or low-pressure hydraulic pilot actuation for pressures up to 6,000 psi liquid or 3,500 psi gas.",
    image: "/images/directional.jpg",
    port: "3/8\"",
    pressurePsi: 6000,
    pressureGasPsi: 3500,
    pressureLabel: psiLabel(6000, 3500),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Gas 4-way control"],
    industries: ["industrial-gas"],
    mounting: "Ported",
    features: ["Soft seated", "Pilot actuated"],
  }),
  p({
    slug: "6b37-h",
    code: "6B37-H",
    name: "Directional Control Valve",
    category: "directional-control-valves",
    summary: "3/8\" 2-position 4-port valve with hydraulic pilot to 10,000 psi.",
    description:
      "3/8\" 2-position 4-port directional control valve with hydraulic pilot for pressures up to 10,000 psi.",
    image: "/images/directional.jpg",
    port: "3/8\"",
    pressurePsi: 10000,
    pressureLabel: "10,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Hydraulic 4-way"],
    industries: ["oil-and-gas", "high-pressure-systems"],
    mounting: "Ported",
    features: ["Hydraulic pilot"],
  }),
  p({
    slug: "6b37-h-g",
    code: "6B37-H-G",
    name: "Directional Control Valve",
    category: "directional-control-valves",
    summary: "3/8\" soft-seated 4-port valve with hydraulic pilot.",
    description:
      "3/8\" 2-position 4-port soft-seated directional control valve with hydraulic pilot actuation for pressures up to 6,000 psi liquid or 3,500 psi gas.",
    image: "/images/directional.jpg",
    port: "3/8\"",
    pressurePsi: 6000,
    pressureGasPsi: 3500,
    pressureLabel: psiLabel(6000, 3500),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Hydraulic 4-way gas service"],
    industries: ["industrial-gas"],
    mounting: "Ported",
    features: ["Soft seated", "Hydraulic pilot"],
  }),

  p({
    slug: "bnv10fc-tb",
    code: "BNV10FC-TB",
    name: "Cartridge Stop Valve",
    category: "stop-metering-valves",
    summary: "Cartridge-style stop valve with T-bar handle and tight shut-off.",
    description:
      "The BNV10FC-TB is a cartridge-style stop valve. It provides tight shut-off when closed via a T-bar handle. Coarse adjustment allows fast operation. The valve may be used with the same functionality in either direction.",
    image: "/images/stop-metering.jpg",
    port: "Cartridge",
    pressurePsi: 10000,
    pressureLabel: "Application rated",
    media: ["Oil", "Water glycol"],
    materials: SS,
    applications: ["Manifold shut-off"],
    industries: ["oil-and-gas", "topside"],
    mounting: "Cartridge",
    features: ["T-bar", "Bi-directional", "Tight shut-off"],
  }),
  p({
    slug: "bnv25",
    code: "BNV25",
    name: "Stop Valve",
    category: "stop-metering-valves",
    summary: "1/4\" stop valve with knurled handwheel and tight shut-off.",
    description:
      "The BNV25 is a 1/4\" nominal bore stop valve. It provides tight shut-off when closed via the knurled handwheel. Coarse adjustment allows fast operation. Marked with a preferred flow direction but equally functional in reverse.",
    image: "/images/stop-metering.jpg",
    port: "1/4\"",
    pressurePsi: 10000,
    pressureGasPsi: 6000,
    pressureLabel: psiLabel(10000, 6000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Isolation", "Panel shut-off"],
    industries: ["oil-and-gas", "high-pressure-systems"],
    mounting: "Inline",
    features: ["Knurled handwheel", "Tight shut-off"],
  }),
  p({
    slug: "bnv25-g",
    code: "BNV25-G",
    name: "Stop Valve",
    category: "stop-metering-valves",
    summary: "1/4\" soft-seated stop valve for liquid or gas.",
    description:
      "The BNV25-G is a 1/4\" nominal bore stop valve with a knurled handwheel. Soft seated for liquid or gas. Uni-directional service only.",
    image: "/images/stop-metering.jpg",
    port: "1/4\"",
    pressurePsi: 10000,
    pressureLabel: "Soft seated, liquid or gas",
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Gas isolation"],
    industries: ["industrial-gas"],
    mounting: "Inline",
    features: ["Soft seated", "Uni-directional"],
  }),
  p({
    slug: "bnv25-tb",
    code: "BNV25-TB",
    name: "Stop Valve",
    category: "stop-metering-valves",
    summary: "1/4\" stop valve with T-bar handle.",
    description:
      "The BNV25-TB is a 1/4\" nominal bore stop valve. Tight shut-off via a T-bar handle. Coarse adjustment for fast operation.",
    image: "/images/stop-metering.jpg",
    port: "1/4\"",
    pressurePsi: 10000,
    pressureGasPsi: 6000,
    pressureLabel: psiLabel(10000, 6000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Isolation"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["T-bar handle"],
  }),
  p({
    slug: "bnv25-37",
    code: "BNV25/37",
    name: "Stop Valve",
    category: "stop-metering-valves",
    summary: "3/8\" stainless stop valve to 10,000 psi liquid / 6,000 psi gas.",
    description:
      "3/8\" stainless steel stop (shut-off) valve for pressures up to 10,000 psi with liquids and 6,000 psi with gas.",
    image: "/images/stop-metering.jpg",
    port: "3/8\"",
    pressurePsi: 10000,
    pressureGasPsi: 6000,
    pressureLabel: psiLabel(10000, 6000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Isolation"],
    industries: ["oil-and-gas", "high-pressure-systems"],
    mounting: "Inline",
    features: ["Tight shut-off"],
  }),
  p({
    slug: "bnv50",
    code: "BNV50",
    name: "Stop Valve",
    category: "stop-metering-valves",
    summary: "1/2\" stop valve with knurled handwheel and extension bars.",
    description:
      "The BNV50 is a 1/2\" nominal bore stop valve. Tight shut-off via the knurled handwheel with extension bars. Coarse adjustment for fast operation.",
    image: "/images/stop-metering.jpg",
    port: "1/2\"",
    pressurePsi: 10000,
    pressureGasPsi: 6000,
    pressureLabel: psiLabel(10000, 6000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Isolation"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Extension bars"],
  }),
  p({
    slug: "bnv50-g",
    code: "BNV50-G",
    name: "Stop Valve",
    category: "stop-metering-valves",
    summary: "1/2\" soft-seated stop valve for liquid or gas.",
    description:
      "The BNV50-G is a 1/2\" nominal bore soft-seated stop valve for liquid or gas. Uni-directional service only.",
    image: "/images/stop-metering.jpg",
    port: "1/2\"",
    pressurePsi: 10000,
    pressureLabel: "Soft seated, liquid or gas",
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Gas isolation"],
    industries: ["industrial-gas"],
    mounting: "Inline",
    features: ["Soft seated"],
  }),
  p({
    slug: "bnv50-75",
    code: "BNV50/75",
    name: "Stop Valve",
    category: "stop-metering-valves",
    summary: "3/4\" stainless stop valve to 10,000 psi liquid / 6,000 psi gas.",
    description:
      "3/4\" stainless steel stop (shut-off) valve for pressures up to 10,000 psi with liquids and 6,000 psi with gas.",
    image: "/images/stop-metering.jpg",
    port: "3/4\"",
    pressurePsi: 10000,
    pressureGasPsi: 6000,
    pressureLabel: psiLabel(10000, 6000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Isolation"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Tight shut-off"],
  }),
  p({
    slug: "bnv44ae",
    code: "BNV44AE",
    name: "Medium Pressure Stop Valve",
    category: "stop-metering-valves",
    summary: "1/4\" OD tube medium-pressure stop valve for pressure testing.",
    description:
      "The BNV44AE is a 1/4\" OD tube medium-pressure ported stop valve with T-bar handle. Elastomeric stem seal design allows long-term use without packing adjustment. Minimised backlash — particularly suited to pressure testing.",
    image: "/images/stop-metering.jpg",
    port: "1/4\" OD tube",
    pressurePsi: 20000,
    pressureLabel: "Medium pressure tube",
    media: ["Oil", "Water", "Nitrogen"],
    materials: SS,
    applications: ["Pressure testing"],
    industries: ["high-pressure-systems"],
    mounting: "Tube",
    features: ["Elastomeric stem seal", "Low backlash"],
  }),
  p({
    slug: "bnv56ae",
    code: "BNV56AE",
    name: "Medium Pressure Stop Valve",
    category: "stop-metering-valves",
    summary: "3/8\" OD tube medium-pressure stop valve.",
    description:
      "The BNV56AE is a 3/8\" OD tube medium-pressure ported stop valve with T-bar handle. Elastomeric stem seal and minimised backlash for pressure testing duty.",
    image: "/images/stop-metering.jpg",
    port: "3/8\" OD tube",
    pressurePsi: 20000,
    pressureLabel: "Medium pressure tube",
    media: ["Oil", "Water", "Nitrogen"],
    materials: SS,
    applications: ["Pressure testing"],
    industries: ["high-pressure-systems"],
    mounting: "Tube",
    features: ["Elastomeric stem seal"],
  }),
  p({
    slug: "bnv81ae",
    code: "BNV81AE",
    name: "Medium Pressure Stop Valve",
    category: "stop-metering-valves",
    summary: "9/16\" OD tube medium-pressure stop valve.",
    description:
      "The BNV81AE is a 9/16\" OD tube medium-pressure ported stop valve with T-bar handle. Elastomeric stem seal for long-term use without packing adjustment.",
    image: "/images/stop-metering.jpg",
    port: "9/16\" OD tube",
    pressurePsi: 20000,
    pressureLabel: "Medium pressure tube",
    media: ["Oil", "Water", "Nitrogen"],
    materials: SS,
    applications: ["Pressure testing"],
    industries: ["high-pressure-systems"],
    mounting: "Tube",
    features: ["Elastomeric stem seal"],
  }),
  p({
    slug: "mf25",
    code: "MF25",
    name: "Fine Flow Metering Valve",
    category: "stop-metering-valves",
    summary: "1/4\" inline fine-flow metering to 8,000 psi liquid / 4,000 psi gas.",
    description:
      "1/4\" stainless steel inline fine-flow metering valve for pressures up to 8,000 psi with liquid and 4,000 psi with gas. Micrometer-style adjustment.",
    image: "/images/stop-metering.jpg",
    port: "1/4\"",
    pressurePsi: 8000,
    pressureGasPsi: 4000,
    pressureLabel: psiLabel(8000, 4000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Speed control", "Orifice adjustment"],
    industries: ["oil-and-gas", "specialist-engineering"],
    mounting: "Inline",
    features: ["Micrometer adjustment"],
  }),
  p({
    slug: "fmf25",
    code: "FMF25",
    name: "Fine Flow Metering Valve",
    category: "stop-metering-valves",
    summary: "1/4\" micrometer metering valve. Not intended for tight shut-off.",
    description:
      "The FMF25 is a 1/4\" nominal bore fine-flow metering valve, adjustable via a micrometer-style handle. May be used in reverse for bi-directional cylinder speed control. Not intended to provide tight shut-off when closed.",
    image: "/images/stop-metering.jpg",
    port: "1/4\"",
    pressurePsi: 8000,
    pressureGasPsi: 4000,
    pressureLabel: psiLabel(8000, 4000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Actuator speed control"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Micrometer handle", "Bi-directional metering"],
  }),
  p({
    slug: "vfmf25",
    code: "VFMF25",
    name: "Very Fine Flow Metering Valve",
    category: "stop-metering-valves",
    summary: "Very fine micrometer metering for precise speed control.",
    description:
      "The VFMF25 is a very fine-flow metering valve, adjustable via a micrometer-style handle. Not intended to provide tight shut-off when closed.",
    image: "/images/stop-metering.jpg",
    port: "1/4\"",
    pressurePsi: 8000,
    pressureLabel: "Fine metering",
    media: ["Oil"],
    materials: SS,
    applications: ["Precision speed control"],
    industries: ["specialist-engineering"],
    mounting: "Inline",
    features: ["Very fine metering"],
  }),
  p({
    slug: "mf37",
    code: "MF37",
    name: "Fine Flow Metering Valve",
    category: "stop-metering-valves",
    summary: "3/8\" inline fine-flow metering to 8,000 psi liquid / 4,000 psi gas.",
    description:
      "3/8\" stainless steel inline fine-flow metering valve for pressures up to 8,000 psi with liquid and 4,000 psi with gas.",
    image: "/images/stop-metering.jpg",
    port: "3/8\"",
    pressurePsi: 8000,
    pressureGasPsi: 4000,
    pressureLabel: psiLabel(8000, 4000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Flow metering"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Micrometer adjustment"],
  }),
  p({
    slug: "mf50",
    code: "MF50",
    name: "Fine Flow Metering Valve",
    category: "stop-metering-valves",
    summary: "1/2\" inline fine-flow metering to 8,000 psi liquid / 4,000 psi gas.",
    description:
      "1/2\" stainless steel inline fine-flow metering valve for pressures up to 8,000 psi with liquid and 4,000 psi with gas.",
    image: "/images/stop-metering.jpg",
    port: "1/2\"",
    pressurePsi: 8000,
    pressureGasPsi: 4000,
    pressureLabel: psiLabel(8000, 4000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Flow metering"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Micrometer adjustment"],
  }),
  p({
    slug: "mf75",
    code: "MF75",
    name: "Fine Flow Metering Valve",
    category: "stop-metering-valves",
    summary: "3/4\" inline fine-flow metering to 8,000 psi liquid / 4,000 psi gas.",
    description:
      "3/4\" stainless steel inline fine-flow metering valve for pressures up to 8,000 psi with liquid and 4,000 psi with gas.",
    image: "/images/stop-metering.jpg",
    port: "3/4\"",
    pressurePsi: 8000,
    pressureGasPsi: 4000,
    pressureLabel: psiLabel(8000, 4000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Flow metering"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Micrometer adjustment"],
  }),
  p({
    slug: "mf100",
    code: "MF100",
    name: "Fine Flow Metering Valve",
    category: "stop-metering-valves",
    summary: "1\" inline fine-flow metering to 8,000 psi liquid / 4,000 psi gas.",
    description:
      "1\" stainless steel inline fine-flow metering valve for pressures up to 8,000 psi with liquid and 4,000 psi with gas.",
    image: "/images/stop-metering.jpg",
    port: "1\"",
    pressurePsi: 8000,
    pressureGasPsi: 4000,
    pressureLabel: psiLabel(8000, 4000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Flow metering"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Micrometer adjustment"],
  }),
  p({
    slug: "cmf25",
    code: "CMF25",
    name: "Fine Flow Metering Valve",
    category: "stop-metering-valves",
    summary: "1/4\" metering with reverse free-flow check.",
    description:
      "1/4\" stainless steel fine-flow metering valve with reverse free-flow check for pressures up to 8,000 psi with liquid and 4,000 psi with gas.",
    image: "/images/stop-metering.jpg",
    port: "1/4\"",
    pressurePsi: 8000,
    pressureGasPsi: 4000,
    pressureLabel: psiLabel(8000, 4000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Meter-in / meter-out"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Reverse free-flow check"],
  }),
  p({
    slug: "cmf37",
    code: "CMF37",
    name: "Fine Flow Metering Valve",
    category: "stop-metering-valves",
    summary: "3/8\" metering with reverse free-flow check.",
    description:
      "3/8\" stainless steel fine-flow metering valve with reverse free-flow check for pressures up to 8,000 psi with liquid and 4,000 psi with gas.",
    image: "/images/stop-metering.jpg",
    port: "3/8\"",
    pressurePsi: 8000,
    pressureGasPsi: 4000,
    pressureLabel: psiLabel(8000, 4000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Meter-in / meter-out"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Reverse free-flow check"],
  }),
  p({
    slug: "cmf50",
    code: "CMF50",
    name: "Fine Flow Metering Valve",
    category: "stop-metering-valves",
    summary: "1/2\" metering with reverse free-flow check to 6,000 psi.",
    description:
      "1/2\" stainless steel fine-flow metering valve with reverse free-flow check for pressures up to 6,000 psi with liquid and 3,000 psi with gas.",
    image: "/images/stop-metering.jpg",
    port: "1/2\"",
    pressurePsi: 6000,
    pressureGasPsi: 3000,
    pressureLabel: psiLabel(6000, 3000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Meter-in / meter-out"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Reverse free-flow check"],
  }),
  p({
    slug: "cmf75",
    code: "CMF75",
    name: "Fine Flow Metering Valve",
    category: "stop-metering-valves",
    summary: "3/4\" metering with reverse free-flow check to 6,000 psi.",
    description:
      "3/4\" stainless steel fine-flow metering valve with reverse free-flow check for pressures up to 6,000 psi with liquid and 3,000 psi with gas.",
    image: "/images/stop-metering.jpg",
    port: "3/4\"",
    pressurePsi: 6000,
    pressureGasPsi: 3000,
    pressureLabel: psiLabel(6000, 3000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Meter-in / meter-out"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Reverse free-flow check"],
  }),
  p({
    slug: "cmf100",
    code: "CMF100",
    name: "Fine Flow Metering Valve",
    category: "stop-metering-valves",
    summary: "1\" metering with reverse free-flow check to 6,000 psi.",
    description:
      "1\" stainless steel fine-flow metering valve with reverse free-flow check for pressures up to 6,000 psi with liquid and 3,000 psi with gas.",
    image: "/images/stop-metering.jpg",
    port: "1\"",
    pressurePsi: 6000,
    pressureGasPsi: 3000,
    pressureLabel: psiLabel(6000, 3000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Meter-in / meter-out"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Reverse free-flow check"],
  }),
  p({
    slug: "imc25",
    code: "IMC25",
    name: "Metering Valve",
    category: "stop-metering-valves",
    summary: "1/4\" inline metering with reverse free-flow check to 8,000 psi.",
    description:
      "1/4\" stainless steel inline metering valve with reverse free-flow check for pressures up to 8,000 psi.",
    image: "/images/stop-metering.jpg",
    port: "1/4\"",
    pressurePsi: 8000,
    pressureLabel: "8,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Flow metering"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Reverse free-flow check"],
  }),
  p({
    slug: "imc37",
    code: "IMC37",
    name: "Metering Valve",
    category: "stop-metering-valves",
    summary: "3/8\" inline metering with reverse free-flow check to 8,000 psi.",
    description:
      "3/8\" stainless steel inline metering valve with reverse free-flow check for pressures up to 8,000 psi.",
    image: "/images/stop-metering.jpg",
    port: "3/8\"",
    pressurePsi: 8000,
    pressureLabel: "8,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Flow metering"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Reverse free-flow check"],
  }),
  p({
    slug: "imc50",
    code: "IMC50",
    name: "Metering Valve",
    category: "stop-metering-valves",
    summary: "1/2\" inline metering with reverse free-flow check to 8,000 psi.",
    description:
      "1/2\" stainless steel inline metering valve with reverse free-flow check for pressures up to 8,000 psi.",
    image: "/images/stop-metering.jpg",
    port: "1/2\"",
    pressurePsi: 8000,
    pressureLabel: "8,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Flow metering"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Reverse free-flow check"],
  }),
  p({
    slug: "pcfr50",
    code: "PCFR50",
    name: "Pressure Compensated Flow Regulator",
    category: "stop-metering-valves",
    summary: "1/2\" regulator holding flow independent of pressure drop, to 10,000 psi.",
    description:
      "1/2\" stainless steel pressure-compensated flow regulator to maintain flow rate independently of pressure drop, for pressures up to 10,000 psi.",
    image: "/images/stop-metering.jpg",
    port: "1/2\"",
    pressurePsi: 10000,
    pressureLabel: "10,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Constant flow under varying load"],
    industries: ["oil-and-gas", "high-pressure-systems"],
    mounting: "Inline",
    features: ["Pressure compensated"],
  }),
  p({
    slug: "pcfr50-37",
    code: "PCFR50/37",
    name: "Pressure Compensated Flow Regulator",
    category: "stop-metering-valves",
    summary: "3/8\" regulator holding flow independent of pressure drop, to 10,000 psi.",
    description:
      "3/8\" stainless steel pressure-compensated flow regulator to maintain flow rate independently of pressure drop, for pressures up to 10,000 psi.",
    image: "/images/stop-metering.jpg",
    port: "3/8\"",
    pressurePsi: 10000,
    pressureLabel: "10,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Constant flow under varying load"],
    industries: ["oil-and-gas", "high-pressure-systems"],
    mounting: "Inline",
    features: ["Pressure compensated"],
  }),

  ...[
    ["C25", "1/4\"", 9000, 3500],
    ["C37", "3/8\"", 9000, 3500],
    ["C50", "1/2\"", 9000, 3500],
    ["C75", "3/4\"", 9000, 3500],
    ["C100", "1\"", 9000, 3500],
    ["C125", "1.1/4\"", 7000, 3500],
    ["C150", "1.1/2\"", 6000, 3500],
  ].map(([code, port, l, g]) =>
    p({
      slug: `check-valve-${String(code).toLowerCase()}`,
      code: String(code),
      name: "Check Valve",
      category: "check-shuttle-valves",
      summary: `${port} stainless check valve to ${Number(l).toLocaleString()} psi liquid / ${Number(g).toLocaleString()} psi gas.`,
      description: `${port} stainless steel check valve for pressures up to ${Number(l).toLocaleString()} psi with liquid and ${Number(g).toLocaleString()} psi with gas.`,
      image: "/images/check.jpg",
      port: String(port),
      pressurePsi: Number(l),
      pressureGasPsi: Number(g),
      pressureLabel: psiLabel(Number(l), Number(g)),
      media: ["Oil", "Gas", "Water glycol"],
      materials: SS,
      applications: ["Non-return", "Isolation"],
      industries: ["oil-and-gas", "high-pressure-systems", "industrial-gas"],
      mounting: "Inline",
      features: ["Poppet check", "Liquid and gas"],
    }),
  ),
  p({
    slug: "nr25",
    code: "NR25",
    name: "Check Valve",
    category: "check-shuttle-valves",
    summary: "1/4\" check valve to 12,000 psi liquid / 6,000 psi gas.",
    description:
      "1/4\" stainless steel check valve for pressures up to 12,000 psi with liquid and 6,000 psi with gas.",
    image: "/images/check.jpg",
    port: "1/4\"",
    pressurePsi: 12000,
    pressureGasPsi: 6000,
    pressureLabel: psiLabel(12000, 6000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["High-pressure non-return"],
    industries: ["high-pressure-systems", "oil-and-gas"],
    mounting: "Inline",
    features: ["12,000 psi"],
  }),
  p({
    slug: "nr25-20k",
    code: "NR25-20K",
    name: "Check Valve",
    category: "check-shuttle-valves",
    summary: "1/4\" check valve to 20,000 psi liquid / 10,000 psi gas.",
    description:
      "1/4\" stainless steel check valve for pressures up to 20,000 psi with liquid and 10,000 psi with gas.",
    image: "/images/check.jpg",
    port: "1/4\"",
    pressurePsi: 20000,
    pressureGasPsi: 10000,
    pressureLabel: psiLabel(20000, 10000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Ultra-high-pressure non-return"],
    industries: ["high-pressure-systems", "downhole"],
    mounting: "Inline",
    features: ["20,000 psi"],
  }),
  p({
    slug: "nr37",
    code: "NR37",
    name: "Check Valve",
    category: "check-shuttle-valves",
    summary: "3/8\" check valve to 12,000 psi liquid / 6,000 psi gas.",
    description:
      "3/8\" stainless steel check valve for pressures up to 12,000 psi with liquid and 6,000 psi with gas.",
    image: "/images/check.jpg",
    port: "3/8\"",
    pressurePsi: 12000,
    pressureGasPsi: 6000,
    pressureLabel: psiLabel(12000, 6000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["High-pressure non-return"],
    industries: ["high-pressure-systems"],
    mounting: "Inline",
    features: ["12,000 psi"],
  }),
  p({
    slug: "nr50",
    code: "NR50",
    name: "Check Valve",
    category: "check-shuttle-valves",
    summary: "1/2\" check valve to 12,000 psi liquid / 6,000 psi gas.",
    description:
      "1/2\" stainless steel check valve for pressures up to 12,000 psi with liquid and 6,000 psi with gas.",
    image: "/images/check.jpg",
    port: "1/2\"",
    pressurePsi: 12000,
    pressureGasPsi: 6000,
    pressureLabel: psiLabel(12000, 6000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["High-pressure non-return"],
    industries: ["high-pressure-systems"],
    mounting: "Inline",
    features: ["12,000 psi"],
  }),
  p({
    slug: "nr50-20k",
    code: "NR50-20K",
    name: "Check Valve",
    category: "check-shuttle-valves",
    summary: "1/2\" check valve to 20,000 psi liquid / 10,000 psi gas.",
    description:
      "1/2\" stainless steel check valve for pressures up to 20,000 psi with liquid and 10,000 psi with gas.",
    image: "/images/check.jpg",
    port: "1/2\"",
    pressurePsi: 20000,
    pressureGasPsi: 10000,
    pressureLabel: psiLabel(20000, 10000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Ultra-high-pressure non-return"],
    industries: ["high-pressure-systems", "downhole"],
    mounting: "Inline",
    features: ["20,000 psi"],
  }),
  p({
    slug: "nr50m",
    code: "NR50M",
    name: "Manifold Check Valve",
    category: "check-shuttle-valves",
    summary: "1/2\" manifold-mounted check to 6,000 psi liquid / 4,000 psi gas.",
    description:
      "1/2\" stainless steel check valve for manifold mounting for pressures up to 6,000 psi with liquid and 4,000 psi with gas.",
    image: "/images/check.jpg",
    port: "1/2\"",
    pressurePsi: 6000,
    pressureGasPsi: 4000,
    pressureLabel: psiLabel(6000, 4000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Manifold non-return"],
    industries: ["oil-and-gas", "topside"],
    mounting: "Manifold",
    features: ["Manifold mounted"],
  }),
  p({
    slug: "nr75",
    code: "NR75",
    name: "Check Valve",
    category: "check-shuttle-valves",
    summary: "3/4\" check valve to 12,000 psi liquid / 6,000 psi gas.",
    description:
      "3/4\" stainless steel check valve for pressures up to 12,000 psi with liquid and 6,000 psi with gas.",
    image: "/images/check.jpg",
    port: "3/4\"",
    pressurePsi: 12000,
    pressureGasPsi: 6000,
    pressureLabel: psiLabel(12000, 6000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["High-pressure non-return"],
    industries: ["high-pressure-systems"],
    mounting: "Inline",
    features: ["12,000 psi"],
  }),
  p({
    slug: "nr100",
    code: "NR100",
    name: "Check Valve",
    category: "check-shuttle-valves",
    summary: "1\" check valve to 9,000 psi liquid / 4,000 psi gas.",
    description:
      "1\" stainless steel check valve for pressures up to 9,000 psi with liquid and 4,000 psi with gas.",
    image: "/images/check.jpg",
    port: "1\"",
    pressurePsi: 9000,
    pressureGasPsi: 4000,
    pressureLabel: psiLabel(9000, 4000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Non-return"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["1\" bore"],
  }),
  p({
    slug: "nr200",
    code: "NR200",
    name: "Check Valve",
    category: "check-shuttle-valves",
    summary: "2\" check valve to 3,800 psi liquid / 3,000 psi gas.",
    description:
      "2\" stainless steel check valve for pressures up to 3,800 psi with liquid and 3,000 psi with gas.",
    image: "/images/check.jpg",
    port: "2\"",
    pressurePsi: 3800,
    pressureGasPsi: 3000,
    pressureLabel: psiLabel(3800, 3000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Large-bore non-return"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["2\" bore"],
  }),
  ...[
    ["CC25", "1/4\"", 10000, 5000],
    ["CC37", "3/8\"", 10000, 5000],
    ["CC50", "1/2\"", 10000, 5000],
    ["CC75", "3/4\"", 10000, 5000],
    ["CC100", "1\"", 6000, 3500],
  ].map(([code, port, l, g]) =>
    p({
      slug: `cartridge-check-${String(code).toLowerCase()}`,
      code: String(code),
      name: "Cartridge Check Valve",
      category: "check-shuttle-valves",
      summary: `${port} cartridge check for hydraulic manifolds.`,
      description: `${port} stainless steel cartridge check valve for use in hydraulic manifolds for pressures up to ${Number(l).toLocaleString()} psi with liquid and ${Number(g).toLocaleString()} psi with gas.`,
      image: "/images/check.jpg",
      port: String(port),
      pressurePsi: Number(l),
      pressureGasPsi: Number(g),
      pressureLabel: psiLabel(Number(l), Number(g)),
      media: ["Oil", "Gas"],
      materials: SS,
      applications: ["Manifold integration"],
      industries: ["oil-and-gas", "topside"],
      mounting: "Cartridge",
      features: ["Cartridge", "Manifold ready"],
    }),
  ),
  p({
    slug: "cv25",
    code: "CV25",
    name: "Venting Check Valve",
    category: "check-shuttle-valves",
    summary: "Stainless vent-to-atmosphere cartridge check valve.",
    description:
      "Stainless steel vent-to-atmosphere style cartridge check valve.",
    image: "/images/check.jpg",
    port: "Cartridge",
    pressurePsi: 6000,
    pressureLabel: "Vent to atmosphere",
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Venting check"],
    industries: ["oil-and-gas"],
    mounting: "Cartridge",
    features: ["Vent to atmosphere"],
  }),
  p({
    slug: "yv25",
    code: "YV25",
    name: "Check Valve with Thermal Relief",
    category: "check-shuttle-valves",
    summary: "1/4\" check with integral reverse thermal relief.",
    description:
      "The YV25 is a ¼\" nominal bore check valve with integral reverse thermal relief. It allows flow in one direction and blocks the opposite unless a preset pressure differential is exceeded — typically used where trapped volume is subject to thermal expansion. Not classed as a PED safety accessory; suitable only where inlet-side volume can accept relieved fluid.",
    image: "/images/check.jpg",
    port: "1/4\"",
    pressurePsi: 10000,
    pressureLabel: "Thermal relief check",
    media: ["Oil"],
    materials: SS,
    applications: ["Thermal expansion protection"],
    industries: ["oil-and-gas", "high-pressure-systems"],
    mounting: "Inline",
    features: ["Integral thermal relief"],
  }),
  p({
    slug: "sv25",
    code: "SV25",
    name: "Shuttle Valve",
    category: "check-shuttle-valves",
    summary: "1/4\" shuttle valve to 10,000 psi — selects the higher of two pressures.",
    description:
      "1/4\" stainless steel shuttle valve for pressures up to 10,000 psi. Selects the higher of two pressures, a function often used when redundancy of pilot systems is required.",
    image: "/images/check.jpg",
    port: "1/4\"",
    pressurePsi: 10000,
    pressureLabel: "10,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Pilot redundancy", "High-pressure select"],
    industries: ["oil-and-gas", "subsea", "topside"],
    mounting: "Inline",
    features: ["High-pressure select"],
  }),
  p({
    slug: "sv25c",
    code: "SV25C",
    name: "Cartridge Shuttle Valve",
    category: "check-shuttle-valves",
    summary: "1/4\" cartridge shuttle valve to 4,000 psi.",
    description:
      "1/4\" stainless steel cartridge-style shuttle valve for pressures up to 4,000 psi.",
    image: "/images/check.jpg",
    port: "1/4\"",
    pressurePsi: 4000,
    pressureLabel: "4,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Manifold shuttle"],
    industries: ["oil-and-gas"],
    mounting: "Cartridge",
    features: ["Cartridge"],
  }),
  p({
    slug: "sv50",
    code: "SV50",
    name: "Shuttle Valve",
    category: "check-shuttle-valves",
    summary: "1/2\" shuttle with sealed poppet — virtually zero leakage on liquid and gas.",
    description:
      "The SV50 is a 1/2\" nominal bore shuttle valve. It senses the higher of two pressures and sends this pressure to the outlet. Sealed poppet technology gives virtually zero leakage with liquids and gases.",
    image: "/images/check.jpg",
    port: "1/2\"",
    pressurePsi: 8000,
    pressureLabel: "Sealed poppet shuttle",
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Pilot redundancy"],
    industries: ["oil-and-gas", "subsea"],
    mounting: "Inline",
    features: ["Zero-leak poppet"],
  }),
  ...[
    ["SV50/25", "1/4\"", 8000, 4000],
    ["SV50/37", "3/8\"", 8000, 4000],
    ["SV50/50", "1/2\"", 8000, 4000],
  ].map(([code, port, l, g]) =>
    p({
      slug: `shuttle-${String(code).toLowerCase().replace("/", "-")}`,
      code: String(code),
      name: "Shuttle Valve",
      category: "check-shuttle-valves",
      summary: `${port} shuttle valve to ${Number(l).toLocaleString()} psi liquid / ${Number(g).toLocaleString()} psi gas.`,
      description: `${port} stainless steel shuttle valve for pressures up to ${Number(l).toLocaleString()} psi with liquid and ${Number(g).toLocaleString()} psi with gas.`,
      image: "/images/check.jpg",
      port: String(port),
      pressurePsi: Number(l),
      pressureGasPsi: Number(g),
      pressureLabel: psiLabel(Number(l), Number(g)),
      media: ["Oil", "Gas"],
      materials: SS,
      applications: ["Pilot redundancy"],
      industries: ["oil-and-gas"],
      mounting: "Inline",
      features: ["High-pressure select"],
    }),
  ),

  ...[
    ["S25", "1/4\"", "0.7–40 bar"],
    ["S37", "3/8\"", "0.7–40 bar"],
    ["S50", "1/2\"", "0.7–40 bar"],
    ["S75", "3/4\"", "0.7–40 bar"],
    ["S100", "1\"", "0.7–18 bar"],
  ].map(([code, port, range]) =>
    p({
      slug: `safety-relief-${String(code).toLowerCase()}`,
      code: String(code),
      name: "Safety Relief Valve (L.P.)",
      category: "relief-valves",
      summary: `${port} vent-to-atmosphere safety relief, set ${range}. PED Category IV.`,
      description: `${port} stainless steel vent-to-atmosphere style safety relief valve for set pressures ${range}, with liquid or gas. Approved as a Safety Accessory to Category IV of the Pressure Equipment Directive 2014/68/EU.`,
      image: "/images/relief.jpg",
      port: String(port),
      pressurePsi: 580,
      pressureLabel: range,
      media: ["Liquid", "Gas"],
      materials: SS,
      applications: ["Safety relief", "Vent to atmosphere"],
      industries: ["oil-and-gas", "industrial-gas", "high-pressure-systems"],
      mounting: "Inline",
      features: ["PED Cat. IV", "Pop-open characteristic"],
    }),
  ),
  ...[
    ["TS25", "1/4\"", "0.7–40 bar"],
    ["TS37", "3/8\"", "0.7–40 bar"],
    ["TS50", "1/2\"", "0.7–40 bar"],
    ["TS75", "3/4\"", "0.7–40 bar"],
    ["TS100", "1\"", "0.7–28 bar"],
  ].map(([code, port, range]) =>
    p({
      slug: `safety-relief-${String(code).toLowerCase()}`,
      code: String(code),
      name: "Safety Relief Valve (L.P.)",
      category: "relief-valves",
      summary: `${port} safety relief, set ${range}. PED Category IV.`,
      description: `${port} stainless steel safety relief valve for set pressures ${range}, with liquid or gas. Approved as a Safety Accessory to Category IV of PED 2014/68/EU.`,
      image: "/images/relief.jpg",
      port: String(port),
      pressurePsi: 580,
      pressureLabel: range,
      media: ["Liquid", "Gas"],
      materials: SS,
      applications: ["Safety relief"],
      industries: ["oil-and-gas", "industrial-gas"],
      mounting: "Inline",
      features: ["PED Cat. IV"],
    }),
  ),
  p({
    slug: "ts25c",
    code: "TS25C",
    name: "Cartridge Relief Valve (L.P.)",
    category: "relief-valves",
    summary: "1/4\" cartridge safety relief for low set pressures. PED Cat. IV.",
    description:
      "1/4\" stainless steel cartridge-style safety relief valve for incorporation into manifolds where low set pressures are required. Approved as a Safety Accessory to Category IV of PED 2014/68/EU.",
    image: "/images/relief.jpg",
    port: "1/4\"",
    pressurePsi: 580,
    pressureLabel: "Low set, cartridge",
    media: ["Liquid", "Gas"],
    materials: SS,
    applications: ["Manifold relief"],
    industries: ["oil-and-gas", "topside"],
    mounting: "Cartridge",
    features: ["PED Cat. IV", "Cartridge"],
  }),
  ...[
    ["RL25", "1/4\"", 15000, false],
    ["RL37", "3/8\"", 15000, false],
    ["RL25-G", "1/4\"", 6000, true],
    ["RL37-G", "3/8\"", 6000, true],
    ["RL50", "1/2\"", 15000, false],
    ["RL50-G", "1/2\"", 6000, true],
    ["RL75", "3/4\"", 15000, false],
    ["RL75-G", "3/4\"", 6000, true],
    ["RL100", "1\"", 3000, false],
    ["RL100-G", "1\"", 3000, true],
  ].map(([code, port, psi, gas]) =>
    p({
      slug: `relief-${String(code).toLowerCase()}`,
      code: String(code),
      name: "Relief Valve (H.P.)",
      category: "relief-valves",
      summary: `${port} ${gas ? "soft-seated " : ""}high-pressure relief to ${Number(psi).toLocaleString()} psi. PED Cat. IV.`,
      description: `${port} stainless steel ${gas ? "relief valve with soft seats" : "relief valve"} for pressures up to ${Number(psi).toLocaleString()} psi${gas ? " with liquid or gas" : ""}. Approved as a Safety Accessory to Category IV of PED 2014/68/EU.`,
      image: "/images/relief.jpg",
      port: String(port),
      pressurePsi: Number(psi),
      pressureLabel: `${Number(psi).toLocaleString()} psi${gas ? " liquid or gas" : ""}`,
      media: gas ? ["Liquid", "Gas"] : ["Oil", "Water glycol"],
      materials: EXOTIC,
      applications: ["High-pressure relief", "Safety accessory"],
      industries: ["high-pressure-systems", "oil-and-gas", "downhole"],
      mounting: "Inline",
      features: ["PED Cat. IV", gas ? "Soft seated" : "Metal seated", "Proportional operation"],
    }),
  ),
  p({
    slug: "rl25c",
    code: "RL25C",
    name: "Cartridge Relief Valve (H.P.)",
    category: "relief-valves",
    summary: "1/4\" cartridge relief to 15,000 psi. PED Cat. IV.",
    description:
      "1/4\" stainless steel cartridge-style relief valve for pressures up to 15,000 psi. Approved as a Safety Accessory to Category IV of PED 2014/68/EU.",
    image: "/images/relief.jpg",
    port: "1/4\"",
    pressurePsi: 15000,
    pressureLabel: "15,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Manifold relief"],
    industries: ["high-pressure-systems", "topside"],
    mounting: "Cartridge",
    features: ["PED Cat. IV", "Cartridge"],
  }),
  p({
    slug: "rl25m",
    code: "RL25M",
    name: "Manifold Relief Valve (H.P.)",
    category: "relief-valves",
    summary: "1/4\" manifold-mounted relief to 15,000 psi. PED Cat. IV.",
    description:
      "1/4\" stainless steel manifold-mounted relief valve for pressures up to 15,000 psi. Approved as a Safety Accessory to Category IV of PED 2014/68/EU.",
    image: "/images/relief.jpg",
    port: "1/4\"",
    pressurePsi: 15000,
    pressureLabel: "15,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Manifold relief"],
    industries: ["high-pressure-systems", "topside"],
    mounting: "Manifold",
    features: ["PED Cat. IV", "Manifold mounted"],
  }),
  p({
    slug: "rl50m",
    code: "RL50M",
    name: "Manifold Relief Valve (H.P.)",
    category: "relief-valves",
    summary: "1/2\" manifold-mounted relief to 15,000 psi. PED Cat. IV.",
    description:
      "1/2\" stainless steel manifold-mounted relief valve for pressures up to 15,000 psi. Approved as a Safety Accessory to Category IV of PED 2014/68/EU.",
    image: "/images/relief.jpg",
    port: "1/2\"",
    pressurePsi: 15000,
    pressureLabel: "15,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Manifold relief"],
    industries: ["high-pressure-systems"],
    mounting: "Manifold",
    features: ["PED Cat. IV"],
  }),
  p({
    slug: "prv75c",
    code: "PRV75C",
    name: "Cartridge Relief Valve (H.P.)",
    category: "relief-valves",
    summary: "3/4\" cartridge relief to 6,000 psi. PED Cat. IV.",
    description:
      "3/4\" stainless steel cartridge-style relief valve for pressures up to 6,000 psi. Approved as a Safety Accessory to Category IV of PED 2014/68/EU.",
    image: "/images/relief.jpg",
    port: "3/4\"",
    pressurePsi: 6000,
    pressureLabel: "6,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Manifold relief"],
    industries: ["oil-and-gas"],
    mounting: "Cartridge",
    features: ["PED Cat. IV"],
  }),

  p({
    slug: "3sv25-37",
    code: "3SV25/37",
    name: "Sensing Valve",
    category: "pressure-sensing-valves",
    summary: "Low-pressure pilot switch from a sensed pressure up to 6,000 psi.",
    description:
      "Sensing valve providing a low-pressure pilot signal switch, dependent on a separate sensed pressure of up to 6,000 psi. Used to send a pilot pressure to actuate another valve when a second service rises or falls beyond a pre-determined pressure.",
    image: "/images/pressure-sensing.jpg",
    port: "1/4\" / 3/8\"",
    pressurePsi: 6000,
    pressureLabel: "6,000 psi sensed",
    media: ["Oil"],
    materials: SS,
    applications: ["Pilot switching", "Sequence control"],
    industries: ["oil-and-gas", "topside", "high-pressure-systems"],
    mounting: "Ported",
    features: ["Independent sensed port", "Pilot output"],
  }),
  p({
    slug: "3sv25-50",
    code: "3SV25/50",
    name: "Sensing Valve",
    category: "pressure-sensing-valves",
    summary: "Low-pressure pilot switch from a sensed pressure up to 6,000 psi.",
    description:
      "Sensing valve providing a low-pressure pilot signal switch, dependent on a separate sensed pressure of up to 6,000 psi.",
    image: "/images/pressure-sensing.jpg",
    port: "1/4\" / 1/2\"",
    pressurePsi: 6000,
    pressureLabel: "6,000 psi sensed",
    media: ["Oil"],
    materials: SS,
    applications: ["Pilot switching"],
    industries: ["oil-and-gas", "topside"],
    mounting: "Ported",
    features: ["Independent sensed port"],
  }),

  p({
    slug: "custom-manifold",
    code: "MANIFOLD",
    name: "Bespoke Manifold Solution",
    category: "manifolds",
    summary: "Circuit packaged into a 316 stainless block for topside or subsea.",
    description:
      "BiS designs and manufactures bespoke manifold solutions for topside and subsea. Typically 316 stainless. Starting from a customer's circuit diagram, the engineering team packages the circuit using valves from the BiS range. Compact, fewer leak points, faster installation, and valves can be serviced without disturbing pipework.",
    image: "/images/manifold.jpg",
    port: "As specified",
    pressurePsi: 10000,
    pressureLabel: "Application rated",
    media: ["Oil", "Water glycol", "Seawater"],
    materials: EXOTIC,
    applications: ["HPU", "Chemical injection", "Subsea control", "Workover"],
    industries: ["topside", "subsea", "oil-and-gas"],
    mounting: "Custom",
    features: ["Reduced leak points", "Service without breaking pipework", "Porting to suit layout"],
  }),
  p({
    slug: "custom-valve",
    code: "BESPOKE",
    name: "Custom Valve Design",
    category: "bespoke",
    summary: "Application-led valves in stainless, super duplex, Monel, Inconel, Hastelloy or titanium.",
    description:
      "Standard catalogue products are a small proportion of total supply. With over 50 years in specialist markets, a suitable product is often available from the back catalogue. When none exists, the engineering team designs the valve for the fluid, pressure, ambient conditions and envelope — including MR0175 / ISO 15156 sour service.",
    image: "/images/bespoke.jpg",
    port: "As specified",
    pressurePsi: 20000,
    pressureLabel: "To 20,000 psi",
    media: ["Oil", "Seawater", "Chemicals", "Gas"],
    materials: EXOTIC,
    applications: ["Unsolved flow-control problems"],
    industries: ["subsea", "downhole", "specialist-engineering", "oil-and-gas"],
    mounting: "As specified",
    features: ["Exotic alloys", "MR0175 / ISO 15156", "Subsea & hyperbaric", "Prototype to production"],
  }),

  ...[
    ["ER25", "1/4\"", true],
    ["ER37", "3/8\"", true],
    ["R25", "1/4\"", false],
    ["R37", "3/8\"", false],
    ["R50", "1/2\"", false],
    ["R75", "3/4\"", false],
    ["R100", "1\"", false],
    ["R150", "1.1/2\"", false],
  ].map(([code, port, adj]) =>
    p({
      slug: `excess-flow-${String(code).toLowerCase()}`,
      code: String(code),
      name: "Excess Flow Valve",
      category: "excess-flow-valves",
      summary: `${port} excess flow valve${adj ? " with external adjustment" : ""} to 6,000 psi liquid / 4,000 psi gas.`,
      description: `${port} stainless steel excess flow valve${adj ? " featuring external adjustment" : ""} for use at pressures up to 6,000 psi with liquid and 4,000 psi with gas. Shuts the line in the event of downstream pipe or hose rupture.`,
      image: "/images/check.jpg",
      port: String(port),
      pressurePsi: 6000,
      pressureGasPsi: 4000,
      pressureLabel: psiLabel(6000, 4000),
      media: ["Oil", "Gas"],
      materials: SS,
      applications: ["Hose rupture protection"],
      industries: ["oil-and-gas", "industrial-gas"],
      mounting: "Inline",
      features: adj ? ["External adjustment", "Rupture shut-off"] : ["Rupture shut-off"],
    }),
  ),

  ...[
    ["F25", "1/4\"", 12000, 10000],
    ["F37", "3/8\"", 12000, 6000],
    ["F50", "1/2\"", 12000, 10000],
    ["F75", "3/4\"", 12000, 6000],
    ["F100", "1\"", 9000, 4000],
    ["F125", "1.1/4\"", 6000, 3000],
    ["F150", "1.1/2\"", 6000, 3000],
    ["F200", "2\"", 6000, 3000],
  ].map(([code, port, l, g]) =>
    p({
      slug: `filter-${String(code).toLowerCase()}`,
      code: String(code),
      name: "In Line Filter",
      category: "filters",
      summary: `${port} valve-protection filter to ${Number(l).toLocaleString()} psi liquid.`,
      description: `${port} stainless steel inline valve-protection filter for pressures up to ${Number(l).toLocaleString()} psi with liquid and ${Number(g).toLocaleString()} psi with gas.`,
      image: "/images/filter.jpg",
      port: String(port),
      pressurePsi: Number(l),
      pressureGasPsi: Number(g),
      pressureLabel: psiLabel(Number(l), Number(g)),
      media: ["Oil", "Gas"],
      materials: SS,
      applications: ["Component protection"],
      industries: ["oil-and-gas", "high-pressure-systems"],
      mounting: "Inline",
      features: ["Valve protection"],
    }),
  ),
  ...[
    ["EF25", "1/4\""],
    ["EF37", "3/8\""],
    ["EF50", "1/2\""],
    ["EF100", "1\""],
    ["EF100/75", "3/4\""],
  ].map(([code, port]) =>
    p({
      slug: `filter-${String(code).toLowerCase().replace("/", "-")}`,
      code: String(code),
      name: "Easy Replacement Filter",
      category: "filters",
      summary: `${port} inline filter with easy-replacement element to 8,000 psi.`,
      description: `${port} stainless steel inline valve-protection filter with easy-replacement element for pressures up to 8,000 psi with liquid and 4,000 psi with gas.`,
      image: "/images/filter.jpg",
      port: String(port),
      pressurePsi: 8000,
      pressureGasPsi: 4000,
      pressureLabel: psiLabel(8000, 4000),
      media: ["Oil", "Gas"],
      materials: SS,
      applications: ["Serviceable filtration"],
      industries: ["oil-and-gas"],
      mounting: "Inline",
      features: ["Easy replacement element"],
    }),
  ),
  p({
    slug: "ef50-dp",
    code: "EF50-DP",
    name: "Easy Replacement Filter",
    category: "filters",
    summary: "1/2\" filter with easy-replacement element and blockage indicator.",
    description:
      "1/2\" stainless steel inline valve-protection filter with easy-replacement element and blockage indicator for pressures up to 8,000 psi with liquid and 4,000 psi with gas.",
    image: "/images/filter.jpg",
    port: "1/2\"",
    pressurePsi: 8000,
    pressureGasPsi: 4000,
    pressureLabel: psiLabel(8000, 4000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Monitored filtration"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Blockage indicator"],
  }),
  p({
    slug: "sf50",
    code: "SF50",
    name: "Simplex Filter",
    category: "filters",
    summary: "1/2\" simplex main-line high-pressure filter to 6,000 psi.",
    description:
      "1/2\" stainless steel simplex main-line high-pressure filter for use up to 6,000 psi.",
    image: "/images/filter.jpg",
    port: "1/2\"",
    pressurePsi: 6000,
    pressureLabel: "6,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Main-line filtration"],
    industries: ["oil-and-gas", "topside"],
    mounting: "Inline",
    features: ["Main line"],
  }),
  p({
    slug: "df50",
    code: "DF50",
    name: "Duplex Filter",
    category: "filters",
    summary: "1/2\" duplex main-line filter with on-line switching to 6,000 psi.",
    description:
      "1/2\" stainless steel duplex main-line high-pressure filter for use up to 6,000 psi, with manual switching between filters to allow servicing without downtime.",
    image: "/images/filter.jpg",
    port: "1/2\"",
    pressurePsi: 6000,
    pressureLabel: "6,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Main-line filtration without downtime"],
    industries: ["oil-and-gas", "topside"],
    mounting: "Inline",
    features: ["On-line service", "Manual changeover"],
  }),

  p({
    slug: "260pr",
    code: "260PR",
    name: "H.P. Radial Piston Pump",
    category: "pumps",
    summary: "High-pressure radial piston pump to 12,000 psi.",
    description:
      "Mild steel high-pressure radial piston pump for pressures up to 12,000 psi. Designed primarily for mineral oil, with limited use on water glycols.",
    image: "/images/high-pressure.jpg",
    port: "Pump",
    pressurePsi: 12000,
    pressureLabel: "12,000 psi",
    media: ["Mineral oil", "Water glycol"],
    materials: ["Mild steel"],
    applications: ["Low-flow high-pressure supply"],
    industries: ["high-pressure-systems", "specialist-engineering"],
    mounting: "Pump",
    features: ["Radial piston", "12,000 psi"],
  }),
  p({
    slug: "520pr",
    code: "520PR",
    name: "H.P. Radial Piston Pump",
    category: "pumps",
    summary: "High-pressure radial piston pump to 12,000 psi.",
    description:
      "Mild steel high-pressure radial piston pump for pressures up to 12,000 psi. Designed primarily for mineral oil, with limited use on water glycols.",
    image: "/images/high-pressure.jpg",
    port: "Pump",
    pressurePsi: 12000,
    pressureLabel: "12,000 psi",
    media: ["Mineral oil", "Water glycol"],
    materials: ["Mild steel"],
    applications: ["Low-flow high-pressure supply"],
    industries: ["high-pressure-systems"],
    mounting: "Pump",
    features: ["Radial piston"],
  }),

  ...["A1", "A2", "A3", "A4"].map((code) =>
    p({
      slug: `actuator-${code.toLowerCase()}`,
      code,
      name: "Diaphragm Air Actuator",
      category: "actuators",
      summary: "Stainless diaphragm-style pneumatic actuator for BiS valve types.",
      description:
        "Stainless steel diaphragm-style pneumatic actuator for use with various actuated valve types.",
      image: "/images/actuator.jpg",
      port: "Actuator",
      pressurePsi: 150,
      pressureLabel: "Pneumatic",
      media: ["Air"],
      materials: SS,
      applications: ["Pneumatic valve actuation"],
      industries: ["oil-and-gas", "topside"],
      mounting: "Valve matched",
      features: ["Diaphragm"],
    }),
  ),
  ...["H0", "H1", "H3"].map((code) =>
    p({
      slug: `actuator-${code.toLowerCase()}`,
      code,
      name: "Piston Hydraulic Actuator",
      category: "actuators",
      summary: "Stainless piston-style hydraulic actuator for BiS valve types.",
      description:
        "Stainless steel piston-style hydraulic actuator for use with various actuated valve types.",
      image: "/images/actuator.jpg",
      port: "Actuator",
      pressurePsi: 3000,
      pressureLabel: "Hydraulic",
      media: ["Oil"],
      materials: SS,
      applications: ["Hydraulic valve actuation"],
      industries: ["oil-and-gas", "subsea"],
      mounting: "Valve matched",
      features: ["Piston"],
    }),
  ),
  p({
    slug: "actuator-l",
    code: "L",
    name: "Manual Lever Actuator",
    category: "actuators",
    summary: "Detented lever actuator for BiS valve types.",
    description:
      "Stainless steel detented lever actuator for use with various actuated valve types.",
    image: "/images/actuator.jpg",
    port: "Actuator",
    pressurePsi: 0,
    pressureLabel: "Manual",
    media: ["—"],
    materials: SS,
    applications: ["Manual operation"],
    industries: ["oil-and-gas"],
    mounting: "Valve matched",
    features: ["Detented"],
  }),
  p({
    slug: "actuator-dl",
    code: "DL",
    name: "Deadman's Lever Actuator",
    category: "actuators",
    summary: "Non-detented deadman's lever actuator.",
    description:
      "Stainless steel non-detented deadman's lever actuator for use with various actuated valve types.",
    image: "/images/actuator.jpg",
    port: "Actuator",
    pressurePsi: 0,
    pressureLabel: "Manual",
    media: ["—"],
    materials: SS,
    applications: ["Fail-safe manual"],
    industries: ["oil-and-gas"],
    mounting: "Valve matched",
    features: ["Non-detented"],
  }),
  p({
    slug: "actuator-c0",
    code: "C0",
    name: "Cam Roller Actuator",
    category: "actuators",
    summary: "Stainless cam roller actuator.",
    description:
      "Stainless steel cam roller actuator for use with various actuated valve types.",
    image: "/images/actuator.jpg",
    port: "Actuator",
    pressurePsi: 0,
    pressureLabel: "Mechanical",
    media: ["—"],
    materials: SS,
    applications: ["Cam operation"],
    industries: ["specialist-engineering"],
    mounting: "Valve matched",
    features: ["Cam roller"],
  }),
  p({
    slug: "actuator-c1",
    code: "C1",
    name: "Cam Pin Actuator",
    category: "actuators",
    summary: "Stainless cam pin actuator.",
    description:
      "Stainless steel cam pin actuator for use with various actuated valve types.",
    image: "/images/actuator.jpg",
    port: "Actuator",
    pressurePsi: 0,
    pressureLabel: "Mechanical",
    media: ["—"],
    materials: SS,
    applications: ["Cam operation"],
    industries: ["specialist-engineering"],
    mounting: "Valve matched",
    features: ["Cam pin"],
  }),
  p({
    slug: "stex1",
    code: "STEX1",
    name: "Solenoid Thruster",
    category: "actuators",
    summary: "ATEX flameproof Ex d hazardous-area solenoid thruster.",
    description:
      "Stainless steel ATEX-approved flameproof EEx d hazardous-area solenoid thruster for use with various solenoid valve types.",
    image: "/images/solenoid.jpg",
    port: "Coil",
    pressurePsi: 0,
    pressureLabel: "ATEX Ex d",
    media: ["—"],
    materials: SS,
    applications: ["Hazardous area solenoid"],
    industries: ["oil-and-gas", "topside"],
    mounting: "Valve matched",
    features: ["ATEX", "Ex d"],
  }),
  p({
    slug: "sw",
    code: "SW",
    name: "Subsea Solenoid Thruster",
    category: "actuators",
    summary: "Solenoid thruster for subsea solenoid valve types.",
    description:
      "Stainless steel solenoid thruster for use with subsea solenoid valve types.",
    image: "/images/solenoid.jpg",
    port: "Coil",
    pressurePsi: 0,
    pressureLabel: "Subsea",
    media: ["Seawater"],
    materials: SS,
    applications: ["Subsea solenoid"],
    industries: ["subsea"],
    mounting: "Valve matched",
    features: ["Subsea rated"],
  }),
  p({
    slug: "hc",
    code: "HC",
    name: "Solenoid Thruster",
    category: "actuators",
    summary: "Hirschmann DIN 43650 connector solenoid thruster.",
    description:
      "Stainless steel solenoid thruster with Hirschmann-style DIN 43650 connector for use with various solenoid valve types.",
    image: "/images/solenoid.jpg",
    port: "Coil",
    pressurePsi: 0,
    pressureLabel: "DIN 43650",
    media: ["—"],
    materials: SS,
    applications: ["Industrial solenoid"],
    industries: ["oil-and-gas"],
    mounting: "Valve matched",
    features: ["DIN 43650"],
  }),
  p({
    slug: "kc",
    code: "KC",
    name: "Solenoid Thruster",
    category: "actuators",
    summary: "Kopex conduit connector solenoid thruster.",
    description:
      "Stainless steel solenoid thruster with Kopex-style conduit connector for use with various solenoid valve types.",
    image: "/images/solenoid.jpg",
    port: "Coil",
    pressurePsi: 0,
    pressureLabel: "Conduit",
    media: ["—"],
    materials: SS,
    applications: ["Industrial solenoid"],
    industries: ["oil-and-gas"],
    mounting: "Valve matched",
    features: ["Kopex conduit"],
  }),

  p({
    slug: "sva12",
    code: "SVA12",
    name: "Pilot Operated Check Valve",
    category: "pilot-operated-check-valves",
    summary: "1/8\" POC with pneumatic or LP hydraulic pilot to 4,000 psi.",
    description:
      "1/8\" stainless steel pilot-operated check valve with pneumatic or low-pressure hydraulic pilot for pressures up to 4,000 psi with liquid and gas.",
    image: "/images/check.jpg",
    port: "1/8\"",
    pressurePsi: 4000,
    pressureLabel: "4,000 psi",
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["Load holding"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Pilot operated"],
  }),
  p({
    slug: "v1-37",
    code: "V1-37",
    name: "Pilot Operated Check Valve",
    category: "pilot-operated-check-valves",
    summary: "3/8\" POC to 20,000 psi liquid / 5,000 psi gas.",
    description:
      "3/8\" stainless steel pilot-operated check valve, available with pneumatic and hydraulic pilot or lever actuation, for pressures up to 20,000 psi with liquid and 5,000 psi with gas.",
    image: "/images/check.jpg",
    port: "3/8\"",
    pressurePsi: 20000,
    pressureGasPsi: 5000,
    pressureLabel: psiLabel(20000, 5000),
    media: ["Oil", "Gas"],
    materials: SS,
    applications: ["High-pressure load holding"],
    industries: ["high-pressure-systems", "downhole"],
    mounting: "Inline",
    features: ["20,000 psi", "Multiple operators"],
  }),
  p({
    slug: "m1-50",
    code: "M1-50",
    name: "Decompression Check Valve",
    category: "pilot-operated-check-valves",
    summary: "1/2\" 2-position 2-port decompression check to 20,000 psi.",
    description:
      "1/2\" 2-position 2-port pilot-operated decompression check valve for pressures up to 20,000 psi. Decays high pressure gently before allowing the valve to fully open.",
    image: "/images/check.jpg",
    port: "1/2\"",
    pressurePsi: 20000,
    pressureLabel: "20,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Shock reduction on dump"],
    industries: ["high-pressure-systems"],
    mounting: "Inline",
    features: ["Decompression"],
  }),
  p({
    slug: "ul75-50",
    code: "UL75/50",
    name: "Unloader Valve",
    category: "pilot-operated-check-valves",
    summary: "1/2\" unloader, pneumatic/LP pilot, lever, push-button or remote vent.",
    description:
      "1/2\" unloader valve, actuated by pneumatic or low-pressure pilot, lever or push button, or remotely by venting a valve on the auxiliary line.",
    image: "/images/check.jpg",
    port: "1/2\"",
    pressurePsi: 12000,
    pressureLabel: "Unloader",
    media: ["Oil"],
    materials: SS,
    applications: ["Pump unload"],
    industries: ["high-pressure-systems"],
    mounting: "Inline",
    features: ["Multiple actuation"],
  }),
  p({
    slug: "ul75",
    code: "UL75",
    name: "Unloader Valve",
    category: "pilot-operated-check-valves",
    summary: "3/4\" unloader with multiple actuation methods.",
    description:
      "3/4\" unloader valve, actuated by pneumatic or low-pressure pilot, lever or push button, or remotely by venting a valve on the auxiliary line.",
    image: "/images/check.jpg",
    port: "3/4\"",
    pressurePsi: 12000,
    pressureLabel: "Unloader",
    media: ["Oil"],
    materials: SS,
    applications: ["Pump unload"],
    industries: ["high-pressure-systems"],
    mounting: "Inline",
    features: ["Multiple actuation"],
  }),
  p({
    slug: "ms75-50",
    code: "MS75/50",
    name: "Pilot Operated Check Valve",
    category: "pilot-operated-check-valves",
    summary: "1/2\" POC with pneumatic, hydraulic and lever actuators to 12,000 psi.",
    description:
      "1/2\" stainless steel pilot-operated check valve with pneumatic, hydraulic pilot and lever actuators for pressures up to 12,000 psi.",
    image: "/images/check.jpg",
    port: "1/2\"",
    pressurePsi: 12000,
    pressureLabel: "12,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Load holding"],
    industries: ["oil-and-gas", "high-pressure-systems"],
    mounting: "Inline",
    features: ["Multiple operators"],
  }),
  p({
    slug: "ms75",
    code: "MS75",
    name: "Pilot Operated Check Valve",
    category: "pilot-operated-check-valves",
    summary: "3/4\" POC with pneumatic, hydraulic and lever actuators to 12,000 psi.",
    description:
      "3/4\" stainless steel pilot-operated check valve with pneumatic, hydraulic pilot and lever actuators for pressures up to 12,000 psi.",
    image: "/images/check.jpg",
    port: "3/4\"",
    pressurePsi: 12000,
    pressureLabel: "12,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Load holding"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Multiple operators"],
  }),
  p({
    slug: "2xpc50-37",
    code: "2XPC50/37",
    name: "Double Pilot Operated Check Valve",
    category: "pilot-operated-check-valves",
    summary: "3/8\" dual POC to 6,000 psi.",
    description:
      "3/8\" stainless steel dual pilot-operated check valve for pressures up to 6,000 psi.",
    image: "/images/check.jpg",
    port: "3/8\"",
    pressurePsi: 6000,
    pressureLabel: "6,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Double-acting load holding"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Dual POC"],
  }),
  p({
    slug: "2xpc50",
    code: "2XPC50",
    name: "Double Pilot Operated Check Valve",
    category: "pilot-operated-check-valves",
    summary: "1/2\" dual POC to 6,000 psi.",
    description:
      "1/2\" stainless steel dual pilot-operated check valve for pressures up to 6,000 psi.",
    image: "/images/check.jpg",
    port: "1/2\"",
    pressurePsi: 6000,
    pressureLabel: "6,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Double-acting load holding"],
    industries: ["oil-and-gas"],
    mounting: "Inline",
    features: ["Dual POC"],
  }),
  p({
    slug: "svt12",
    code: "SVT12",
    name: "Midget Lever Operated Check Valve",
    category: "pilot-operated-check-valves",
    summary: "1/8\" lever-operated check to 2,000 psi.",
    description:
      "1/8\" stainless steel lever-operated check valve for pressures up to 2,000 psi.",
    image: "/images/check.jpg",
    port: "1/8\"",
    pressurePsi: 2000,
    pressureLabel: "2,000 psi",
    media: ["Oil"],
    materials: SS,
    applications: ["Compact manual check"],
    industries: ["specialist-engineering"],
    mounting: "Inline",
    features: ["Lever operated"],
  }),
];

export function getCategory(slug: string) {
  return categories.find((c) => c.slug === slug);
}

export function getProduct(category: string, slug: string) {
  return products.find((p) => p.category === category && p.slug === slug);
}

export function productsIn(category: string) {
  return products.filter((p) => p.category === category);
}

export function relatedProducts(product: Product, limit = 3) {
  return products
    .filter((p) => p.category === product.category && p.slug !== product.slug)
    .slice(0, limit);
}

export const pressureBands = [
  { id: "lt3k", label: "Up to 3,000 psi", max: 3000 },
  { id: "3to6", label: "3,000–6,000 psi", min: 3000, max: 6000 },
  { id: "6to10", label: "6,000–10,000 psi", min: 6000, max: 10000 },
  { id: "gt10", label: "10,000+ psi", min: 10000 },
] as const;

export const allMaterials = [
  "316 stainless steel",
  "Super duplex",
  "Monel",
  "Inconel",
  "Hastelloy",
  "Titanium",
];

export const allMedia = ["Oil", "Gas", "Water glycol", "Seawater", "Chemicals", "Air"];

